version: '3'
services:
 web_api:
    container_name: ontologyAPI
    build: ./APIContextInteraction/APIContextInteraction_Java
    ports:
      - "8080:8080"
    network_mode: "host"
 database:
    container_name: graphdb
    image: ontotext/graphdb:10.0.0    

    environment:
      GRAPHDB_JAVA_OPTIONS: -Xmx1g
    ports:
      - "7200:7200"
    volumes:
      # Change folders in the .env file or directly here  
      - ${GRAPHDB_HOME}:/opt/graphdb/home    
      - ${REPOSITORY_CONFIG_FILE}:/opt/graphdb/graphdb-repo-config.ttl
      - ${IMPORT_FOLDER}:/opt/graphdb/home/graphdb-import  
    network_mode: "host"
 database_user:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interactions
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 backend:
    container_name: graphql
    build: 
      context: ${APPLICATION_FOLDER}/server-backenddrivenUI
    ports:
      - "4000:4000"  
 nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
