version: '3'
services:
  web_api:
    build: ./APIContextInteraction/APIContextInteraction_Java
    ports:
      - "8080:8080"
  database:
    image: ontotext/graphdb:10.0.0
    environment:
      GRAPHDB_JAVA_OPTIONS: -Xmx1g
    ports:
      - "7200:7200"
    volumes:
      # Change folders in the .env file or directly here  
      - ${GRAPHDB_HOME}:/opt/graphdb/home    
      - ${REPOSITORY_CONFIG_FILE}:/opt/graphdb/graphdb-repo-config.ttl  
  backend:
    build: ${APPLICATION_FOLDER}/server-backenddrivenUI
    ports:
      - "4000:4000"
  frontend:
    build: ${APPLICATION_FOLDER}/web-backenddrivenui
    ports:
      - "3000:3000"

